#!/bin/bash
npm install @material-ui/core --save
npm install @material-ui/data-grid --save
npm install @material-ui/icons --save
npm install @material-ui/lab --save
npm install @material-ui/lab/Alert --save
npm install @material-ui/lab/Autocomplete --save
npm install @material-ui/lab/TreeItem --save
npm install @material-ui/lab/TreeView --save
npm install @testing-library/react --save
npm install axios --save
npm install clsx --save
npm install formik --save
npm install immer --save
npm install lodash --save
npm install moment --save
npm install prop-types --save
npm install query-string --save
npm install react --save
npm install react-beautiful-dnd --save
npm install react-dom --save
npm install react-redux --save
npm install react-router-dom --save
npm install react-slick --save
npm install react-swipeable-views --save
npm install redux --save
npm install redux-devtools-extension --save
npm install redux-thunk --save
npm install styled-components --save
npm install uuid --save
npm install victory --save
npm install yup --save