/* ========================================================================== *
 * Copyright (C) 2023, 2026 HCL America Inc.                                  *
 * All rights reserved.                                                       *
 * Licensed under Apache 2 License.                                           *
 * ========================================================================== */

import type { Dispatch } from '@reduxjs/toolkit';
import { AppProp, INIT_STATE } from './types';
import { SETUP_KEEP_API_URL } from '../../config.dev';
import { getToken } from '../account/action';
import { toggleAlert } from '../alerts/action';
import { toggleApplicationDrawer } from '../drawer/action';
import { apiRequestWithRetry, errorMessageOf, parseThrownError } from '../../utils/api-retry';
import { getLogger } from '../../services/log-service';
import { toggleDeleteDialog } from '../dialog/action';
// `updateApp` is a thunk in this module and `executing` was a hand-written creator;
// the generated action of the same name is aliased so callers keep the thunk.
import {
  addApp,
  deleteApp,
  executing,
  getApps,
  setPulledApp,
  updateApp as updateAppAction
} from './reducer';

export { executing };

const log = getLogger('store/applications');

/**
 * A second creator for the dialog slice's own action, kept because callers import
 * it from here. It re-exports rather than rebuilding the action: once the reducer
 * answers to `dialog/toggleDeleteDialog`, hand-rolling the raw type here would be
 * a silent no-op.
 */
export { toggleDeleteDialog };

/**
 * Retrieves the arrays of Applications and
 * passes them to Redux.
 */
export const fetchMyApps = () => {
  return async (dispatch: Dispatch) => {
    try {
      const { response, data } = await apiRequestWithRetry(() =>
        fetch(`${SETUP_KEEP_API_URL}/admin/applications`, {
          headers: {
            Authorization: `Bearer ${getToken()}`,
            Accept: 'application/json'
          }
        }), { notifyOnError: false })
      if (!response.ok) {
        throw new Error(JSON.stringify(data.message))
      }
      const appsList: Array<AppProp> = [];

      // Set Application state
      data.forEach((app: any) => {
        appsList.push({
          appName: app.client_name,
          appDescription: app.description,
          appCallbackUrls: app.redirect_uris,
          appContacts: app.contacts,
          appId: app.client_id,
          appIcon: app.logo_uri,
          appScope: app.scope,
          appHasSecret: app.hasSecret,
          appSecret: app.client_secret,
          appStartPage: app.client_uri,
          appStatus: app.status,
          usePkce: app.token_endpoint_auth_method === 'none',
        });
      });

      dispatch(getApps(appsList));
      dispatch(setPullApp(true));
    } catch (err: any) {
      // Use the Keep response error if it's available
      if (err) {
        dispatch(
          toggleAlert(`Error Fetching Apps: ${err}`)
        );
      }
      // Otherwise use the generic error
      else {
        dispatch(toggleAlert(`Error Fetching Apps: ${err}`));
      }
    }
  };
};

// A commented-out `dropUpdate` thunk sat here and is deleted (#869). It could not be
// revived as written: it called `axios`, which stopped being a dependency, and its catch
// dispatched `setAppError`, which this commit removes. The live drag-and-drop path is the
// `dropUpdate` action generated by the slice.
/**
 * Update an Application and check for errors
 */
export function updateApp(appData: any) {
  return async (dispatch: Dispatch) => {
    try {
      // Based on API verb, this is now PUT instead of patch
      const { response, data } = await apiRequestWithRetry(() =>
        fetch(`${SETUP_KEEP_API_URL}/admin/application/${appData.client_id}`, {
          method: 'PUT',
          headers: {
            Authorization: `Bearer ${getToken()}`,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            ...appData,
            isActive: appData.status,
          }),
        }), { notifyOnError: false })
      const res = response
      if (!res.ok) {
        throw new Error(JSON.stringify(data.message))
      }

      const appReduxData: AppProp = {
        appName: data.client_name,
        appDescription: data.description,
        appCallbackUrls: data.redirect_uris,
        appContacts: data.contacts,
        appId: data.client_id,
        appIcon: data.logo_uri,
        appScope: data.scope,
        appHasSecret: data.hasSecret ? true : false,
        appSecret: data.client_secret,
        appStartPage: data.client_uri,
        appStatus: data.status,
        usePkce: data.token_endpoint_auth_method === 'none',
      };
      dispatch(updateAppAction(appReduxData));
      dispatch(toggleApplicationDrawer());
      dispatch(toggleAlert(`${appData.client_name} has been updated!`));
    } catch (err: any) {
      // Use the Keep response error if it's available
      if (err) {
        dispatch(
          toggleAlert(`Error Updating App: ${err}`)
        );
      }
      // Otherwise use the generic error
      else {
        dispatch(toggleAlert(`Error Updating App: ${err}`));
      }
    }
  };
}

export function getSingleApp(appId: string) {
  return async (dispatch: Dispatch) => {
    try {
      const { response, data } = await apiRequestWithRetry(() =>
        fetch(`${SETUP_KEEP_API_URL}/admin/application/${appId}`, {
          headers: {
            Authorization: `Bearer ${getToken()}`,
            'Content-Type': 'application/json'
          }
        }), { notifyOnError: false })
      const res = response
      if (!res.ok) {
        throw new Error(JSON.stringify(data.message))
      }

      const appReduxData: AppProp = {
        appName: data.client_name,
        appDescription: data.description,
        appCallbackUrls: data.redirect_uris,
        appContacts: data.contacts,
        appId: data.client_id,
        appIcon: data.logo_uri,
        appScope: data.scope,
        appHasSecret: data.hasSecret ? true : false,
        appSecret: data.client_secret,
        appStartPage: data.client_uri,
        appStatus: data.status,
        usePkce: data.token_endpoint_auth_method === 'none',
      };
      dispatch(updateAppAction(appReduxData));
    } catch (err: any) {
      // Use the Keep response error if it's available
      if (err) {
        dispatch(
          toggleAlert(`Error Updating App: ${err}`)
        );
      }
      // Otherwise use the generic error
      else {
        dispatch(toggleAlert(`Error Updating App: ${err}`));
      }
    }
  };
}

/**
 * Delete an Application and check for errors
 */
export function deleteApplication(appId: string) {
  return async (dispatch: Dispatch) => {
    dispatch(executing(true));

    try {
      const { response, data } = await apiRequestWithRetry(() =>
        fetch(`${SETUP_KEEP_API_URL}/admin/application/${appId}`, {
          method: 'DELETE',
          headers: {
            Authorization: `Bearer ${getToken()}`,
            'Content-Type': 'application/json'
          },
        }), { notifyOnError: false })
      if (!response.ok) {
        throw new Error(JSON.stringify(data.message))
      }

      dispatch(deleteApp(appId));
      dispatch(toggleDeleteDialog());
      dispatch(toggleAlert(`Application Deleted`));
    } catch (err: any) {
      // Close the Delete confirmation Dialog
      dispatch(toggleDeleteDialog());
      // Use the Keep response error if it's available
      if (err) {
        dispatch(
          toggleAlert(`Error Deleting App: ${err}`)
        );
      }
      // Otherwise use the generic error
      else {
        dispatch(toggleAlert(`Error Deleting App: ${err}`));
      }
    }
  };
}

/**
 * Create an Application and check for errors
 */
export function addApplication(appData: any) {
  return async (dispatch: Dispatch) => {
    dispatch(executing(true));
    try {
      const { response, data } = await apiRequestWithRetry(() =>
        fetch(`${SETUP_KEEP_API_URL}/admin/application`, {
          method: 'POST',
          headers: {
            Authorization: `Bearer ${getToken()}`,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(appData),
        }), { notifyOnError: false })
      const res = response
      if (!res.ok) {
        throw new Error(JSON.stringify(data.message))
      }

      const appReduxData: AppProp = {
        appName: data.client_name,
        appDescription: data.description,
        appCallbackUrls: data.redirect_uris,
        appContacts: data.contacts,
        appId: data.client_id,
        appIcon: data.logo_uri,
        appScope: data.scope,
        appHasSecret: data.hasSecret,
        appSecret: data.client_secret,
        appStartPage: data.client_uri,
        appStatus: data.status,
        usePkce: data.token_endpoint_auth_method === 'none',
      };
      dispatch(addApp(appReduxData));
      dispatch(toggleApplicationDrawer());
      dispatch(toggleAlert(`New Application Added`));
    } catch (err: any) {
      // Use the Keep response error if it's available
      if (err.response && err.response.statusText) {
        dispatch(toggleAlert(`Error adding App: ${err}`));
      }
      // Otherwise use the generic error
      else {
        dispatch(toggleAlert(`Error adding App: ${err}`));
      }
    }
  };
}

// The application-error pair lived here and is deleted (#869). `setAppError` had been
// commented out along with both its dispatch sites, so nothing set the field; the only
// thing that ever reached the reducer case was `databases`' `SET_DB_ERROR`, which shared
// the value until #866 renamed it. `clearAppError` therefore cleared something nothing
// wrote. Application failures report through `toggleAlert`, as the catch blocks above do.

/**
 * Set applications pulled flag
 */
export const setPullApp = (appPull: boolean) => {
  return setPulledApp(appPull);
};

/**
 * Generate application secret
 * @param appId     the application ID
 * @param appStatus the application status
 */
export const generateSecret = (
  appId: string,
  appStatus: string,
  setGenerating: (generating: boolean) => void,
  setAppSecret: (appSecret: string) => void,
)  => {
  return async (dispatch: Dispatch) => {
    setGenerating(true)

    try {
      const { response, data } = await apiRequestWithRetry(() =>
        fetch(`${SETUP_KEEP_API_URL}/admin/application/${appId}/secret?force=true`, {
          method: 'POST',
          headers: {
            Authorization: `Bearer ${getToken()}`,
            'Content-Type': 'application/json',
          },
          // force=true overwrites any existing secret unconditionally. Callers must
          // confirm with the user before dispatching this (#740).
          body: JSON.stringify({ status: appStatus })
        }), { notifyOnError: false })

      if (!response.ok) {
        throw new Error(JSON.stringify(data))
      }
      setGenerating(false);
      setAppSecret(data.client_secret);
    } catch (e: any) {
      // Always clear the spinner. Without this the caller is left rendering
      // "Generating New Secret …" forever on any failure.
      setGenerating(false);

      // Only the `!response.ok` throw above carries a JSON body. A network failure or a
      // non-JSON error page reaches here as plain text, and parsing it unguarded threw
      // *inside* the catch — so the user saw no alert at all, exactly when one was needed.
      // This site was fixed by hand first; #1000 found the same bug at 24 more and moved the
      // logic to `parseThrownError`, so there is one implementation rather than a pattern to
      // copy. Behaviour here is unchanged.
      const error = parseThrownError(e);

      dispatch(toggleAlert(`Error Generating App Secret: ${error.message}`));
      log.error('Error generating app secret', { error: errorMessageOf(e) })
    }
  }
}

/**
 * Init applications state
 */
export const initApplicationState = () => {
  return {
    type: INIT_STATE
  };
};