/* ========================================================================== *
 * Copyright (C) 2019, 2026 HCL America Inc.                                  *
 * All rights reserved.                                                       *
 * Licensed under Apache 2 License.                                           *
 * ========================================================================== */

import { html, css } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import '@awesome.me/webawesome/dist/components/icon/icon.js';
import { FA_LIBRARY } from '../../services/icon-library';
import { KeepElement } from './keep-element';

/** Payload of the `search-change` event. */
export interface KeepSearchChangeDetail {
  /** The field's text as typed, verbatim — not trimmed, not lower-cased. */
  value: string;
}

/**
 * The filter box that sits above a list: a magnifying glass and one text field.
 * Tag: `keep-search-input`. Exposed to React as `KeepSearchInput`.
 *
 * ## One element, three former files
 *
 * `ViewSearch.tsx`, `AgentSearch.tsx` and `FormSearch.tsx` were the same 41-line component
 * written out three times. Byte for byte the only differences were the placeholder string,
 * the name of the callback prop, and — for the third — which boolean of the databases slice
 * gated pointer events. All three are parameters here, so the element replaces all three.
 *
 * ## The value contract: this field is uncontrolled, deliberately
 *
 * There is **no `value` property**, and adding one would be a bug rather than a feature.
 * The wrapper generated by `@lit/react` re-applies every declared property on every render
 * of the parent with no dirty check, so a `value` fed from parent state would be written
 * back into the field on the render that the user's own keystroke triggered — overwriting
 * whatever they had typed since. The originals were uncontrolled inputs for the same
 * reason, and this keeps that: the element owns its text, and the parent learns about it
 * only through {@link KeepSearchChangeDetail}. A call site must therefore never pass
 * `value`, and there is nothing named `value` for it to pass.
 *
 * ## Where the state lives
 *
 * Nowhere in here. Both surviving parents already select the databases slice for their own
 * lists, so the gating flag arrives as {@link disabled} and the typed text leaves as an
 * event. A store subscription in this leaf would fight the parent's re-render for the same
 * no-dirty-check reason as above.
 *
 * ## Styling
 *
 * Everything below used to reach these three files through the light DOM and therefore
 * stops at the shadow boundary: the three Linaria blocks in `styles/search.tsx`
 * (`FormSearchContainer`, `SearchContainer`, `SearchInput`), the `pointer-auto` /
 * `pointer-none` and `color-text-primary` utilities in `styles.css`, and — least obviously —
 * the whole of WebAwesome's `wa-native` layer, which styles every text input through a bare
 * `input` selector and the box-sizing reset through a universal one.
 *
 * Two `!important` flags are dropped rather than carried over. They were on the container's
 * border-radius and background, and inside a shadow root there is nothing left for them to
 * outrank.
 */
@customElement('keep-search-input')
export default class SearchInput extends KeepElement {
  static styles = css`
    /* FormSearchContainer, styles/search.tsx. */
    :host {
      display: flex;
      flex: 1;
      box-sizing: border-box;
      height: 43px;
      justify-content: center;
      border: 1px solid var(--wa-color-surface-border);
      border-radius: var(--wa-border-radius-l);
      background: var(--wa-color-surface-raised);
    }

    /*
     * The page's border-box reset is WebAwesome's wa-native layer, which sets
     * box-sizing: inherit through a universal selector. A universal selector does not
     * cross a shadow boundary, so without this the field falls back to content-box and
     * its width of 100% stops covering its own inline padding — two extra em of overflow
     * inside a 43px row.
     */
    *,
    *::before,
    *::after {
      box-sizing: border-box;
    }

    /*
     * The pointer-none / pointer-auto pair the original toggled on the container. The
     * enabled half is spelt out rather than left to the initial value because the utility
     * was: pointer-events inherits, so pointer-auto is what let the box stay live inside
     * an ancestor that had switched pointers off.
     */
    :host {
      pointer-events: auto;
    }

    :host([disabled]) {
      pointer-events: none;
    }

    /* SearchContainer, styles/search.tsx. */
    .search-container {
      display: flex;
      align-items: center;
      padding: 0;
      width: 100%;
    }

    /*
     * The .search-icon rule from the same module. canvas is set to auto on the tag rather
     * than here: it is an attribute, not a style, and WebAwesome's own default of fixed is
     * a 1.25em box that would widen the glyph by a quarter.
     */
    .search-icon {
      margin-left: 10px;
      font-size: 19px;
      color: var(--wa-color-text-normal);
    }

    input {
      /*
       * WebAwesome's wa-native layer, restated. Its selector is a bare element one so it
       * does not reach in here, but the tokens it reads are custom properties, which do
       * inherit across the boundary and stay mode-aware.
       */
      height: var(--wa-form-control-height);
      padding: 0 var(--wa-form-control-padding-inline);
      font-family: inherit;
      font-weight: var(--wa-form-control-value-font-weight);
      line-height: var(--wa-form-control-value-line-height);
      vertical-align: middle;
      cursor: text;

      /* SearchInput, styles/search.tsx — unlayered, so it outranked the block above. */
      width: 100%;
      border: 0;
      background: none;
      font-size: 16px;

      /*
       * The utility here was color-text-primary, whose light value is the literal #000 and
       * whose dark override is a light-DOM descendant selector that cannot reach a shadow
       * root — copying the literal would render near-black text on a near-black field.
       * --wa-color-text-normal is the mode-aware token keep-theme.css pins to this
       * palette's primary text colour, and is the substitution keep-zero-results already
       * made for the same utility.
       */
      color: var(--wa-color-text-normal);
    }

    input::placeholder {
      color: var(--wa-form-control-placeholder-color);
      user-select: none;
      -webkit-user-select: none;
    }

    /*
     * The Linaria block set outline: none unconditionally, so the field had no visible focus
     * indicator for anyone driving it from the keyboard (WCAG 2.4.7). Worse, it was unlayered
     * and WebAwesome's focus rule is layered, so the removal won on specificity grounds that
     * had nothing to do with intent.
     *
     * The ring is drawn on the host rather than on the input, so it traces the rounded
     * container the user actually sees as "the field" instead of the invisible box inside it.
     * The offset is negative so it sits inside the container's own border rather than
     * spilling over it, and an outline follows border-radius, so it picks up the curve.
     */
    input:focus {
      outline: none;
    }

    :host(:focus-within) {
      outline: var(--wa-focus-ring);
      outline-offset: calc(-1 * var(--wa-focus-ring-width));
    }
  `;

  /** Prompt shown in the empty field, e.g. `Search Views`. */
  @property({ type: String }) accessor placeholder = '';

  /**
   * Accessible name for the field. Falls back to {@link placeholder}.
   *
   * The originals had none at all: a placeholder is not a label — it is announced
   * inconsistently and vanishes as soon as there is text in the field.
   */
  @property({ type: String }) accessor label = '';

  /**
   * Blocks pointer input, matching the `pointer-none` class the originals toggled from a
   * store flag while the list behind them was still loading.
   *
   * It is **not** the field's `disabled` state: as before, the field stays in the tab order
   * and stays typeable from the keyboard. Reflected, because the rule that implements it is
   * an attribute selector on the host.
   */
  @property({ type: Boolean, reflect: true }) accessor disabled = false;

  render() {
    return html`
      <div class="search-container" role="search">
        <wa-icon
          class="search-icon"
          library=${FA_LIBRARY}
          name="magnifying-glass"
          canvas="auto"
        ></wa-icon>
        <input
          type="text"
          placeholder=${this.placeholder}
          aria-label=${this.label || this.placeholder}
          @input=${this._handleInput}
        >
      </div>
    `;
  }

  private _handleInput(e: Event): void {
    this.emit<KeepSearchChangeDetail>('search-change', {
      value: (e.target as HTMLInputElement).value,
    });
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'keep-search-input': SearchInput;
  }
}
