name: Publish package to Github registry

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to ghcr.io
    runs-on: ubuntu-latest
    env:
      REACT_APP_ADMIN_UI_BUILD_VERSION: ${{ github.run_number }}
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'temurin'
      - run: mvn --no-transfer-progress clean
      - run: npm ci
      - run: npm run build
      - run: npm run test
      - name: Publish mvn to GitHub Packages
        run: mvn --no-transfer-progress deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
