name: Publish package to Github registry

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'temurin'
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: mvn --no-transfer-progress clean
      - run: npm ci
      - run: npm run test
      - name: Publish to GitHub Packages Apache Maven
        run: mvn --batch-mode --no-transfer-progress deploy
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TO_GHCR }}
