name: Release Build and Publish

on:
  push:
    branches:
      - 'v1.1.7.5' # Replace with your exact branch name if different

jobs:
  release:
    name: Release Build to ghcr.io
    runs-on: ubuntu-latest
    env:
      REACT_APP_ADMIN_UI_BUILD_VERSION: ${{ github.run_number }}
      WS_USERKEY: ${{ secrets.WSS_USER_KEY }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout release branch
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          registry-url: 'https://npmjs.org'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'temurin'

      - name: Clean Maven
        run: mvn --no-transfer-progress clean

      - name: Install npm dependencies
        run: npm ci

      - name: Build React app
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Set release product name
        run: echo "PRODUCT_NAME=HCL Labs Project KEEP ${{ steps.get_version.outputs.RELEASE_VERSION }}" >> $GITHUB_ENV

      - name: Check environment variables
        run: echo "version = ${{ steps.get_version.outputs.RELEASE_VERSION }}, product = $PRODUCT_NAME"

      - name: Set Mend Product name
        run: echo "WS_PRODUCTNAME=${{ env.PRODUCT_NAME }}" >> $GITHUB_ENV

      - name: Run Mend Scan (Release)
        uses: TheAxZim/Whitesource-Scan-Action@v1.0.0
        with:
          wssURL: https://saas.whitesourcesoftware.com/agent
          apiKey: ${{ secrets.WSS_API_KEY }}
          configFile: 'admin-wss.config'

      - name: Build Maven package
        run: mvn --no-transfer-progress package -DskipTests

      - name: Publish release to GitHub Packages
        run: mvn --no-transfer-progress deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
